import { createFileRoute } from '@tanstack/react-router';
import { useState } from 'react';
import { Eye, MousePointer2, ShoppingBag, Wallet, ArrowUpRight, Download, Instagram, Youtube, Globe } from 'lucide-react';
import { AdminShell } from '@/components/admin/AdminShell';
import { RangePicker, SalesChart, SectionHeading, Stat } from '@/components/admin/Widgets';
import { Button } from '@/components/ui/button';
import { exportCSV } from '@/lib/admin-data';
export const Route = createFileRoute('/analytics')({head:()=>({meta:[{title:'Analitik — Sety'},{name:'description',content:'Gelir, trafik kaynakları, dönüşüm ve ürün performansını karşılaştırın.'},{property:'og:title',content:'Analitik — Sety'},{property:'og:description',content:'Mağazanızın büyüme fırsatlarını verilerle keşfedin.'},{property:'og:type',content:'website'},{name:'twitter:card',content:'summary_large_image'}]}),component:AnalyticsPage});
function AnalyticsPage(){const [range,setRange]=useState('Son 30 gün');const [metric,setMetric]=useState('Gelir');const multiplier=range==='Son 7 gün'?.25:range==='Son 90 gün'?2.8:1;const sources=[{name:'Instagram',icon:Instagram,percent:64,count:8222},{name:'TikTok',icon:MousePointer2,percent:21,count:2698},{name:'YouTube',icon:Youtube,percent:10,count:1285},{name:'Doğrudan',icon:Globe,percent:5,count:642}];return <AdminShell title="Analitik" action={<div className="flex gap-2"><Button variant="outline" size="icon" aria-label="Raporu indir" title="Raporu indir" onClick={()=>exportCSV('sety-analitik',[['Dönem','Kaynak','Ziyaretçi','Pay'],...sources.map(s=>[range,s.name,String(Math.round(s.count*multiplier)),String(s.percent)+'%'])])}><Download/></Button><RangePicker value={range} onChange={setRange}/></div>}><div className="mb-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Stat label="Ziyaretçiler" value={Math.round(12847*multiplier).toLocaleString('tr')} change="%9,4" icon={<Eye className="h-4 w-4"/>}/><Stat label="Ürün tıklamaları" value={Math.round(4286*multiplier).toLocaleString('tr')} change="%16,8" icon={<MousePointer2 className="h-4 w-4"/>}/><Stat label="Satışlar" value={Math.round(214*multiplier).toLocaleString('tr')} change="%12,1" icon={<ShoppingBag className="h-4 w-4"/>}/><Stat label="Gelir" value={`₺${Math.round(48320*multiplier).toLocaleString('tr')}`} change="%18,2" icon={<Wallet className="h-4 w-4"/>}/></div>
 <section className="rounded-lg border border-border bg-card p-6"><SectionHeading title="Mağaza performansı" subtitle={range} action={<div className="flex rounded bg-muted p-1">{['Gelir','Ziyaretçiler','Satışlar'].map(v=><Button key={v} variant="ghost" size="sm" className={`text-[10px] ${metric===v?'bg-card shadow-sm':'text-muted-foreground'}`} onClick={()=>setMetric(v)}>{v}</Button>)}</div>}/><SalesChart range={range} metric={metric}/></section>
 <div className="mt-7 grid gap-7 lg:grid-cols-2"><section><SectionHeading title="Trafik kaynakları" subtitle="Kitlen seni nereden buluyor?"/><div className="rounded-lg border border-border bg-card p-5"><div className="mb-6 flex h-3 overflow-hidden rounded-full"><span className="w-[64%] bg-primary"/><span className="w-[21%] bg-volt"/><span className="w-[10%] bg-success"/><span className="w-[5%] bg-muted"/></div><div className="space-y-5">{sources.map(({name,icon:I,percent,count})=><div key={name} className="flex items-center gap-3"><span className="grid h-8 w-8 place-items-center rounded bg-muted text-muted-foreground"><I className="h-4 w-4"/></span><span className="flex-1 text-xs font-medium">{name}</span><span className="text-[11px] text-subtle">{Math.round(count*multiplier).toLocaleString('tr')}</span><span className="w-10 text-right text-xs font-semibold">%{percent}</span></div>)}</div></div></section><section><SectionHeading title="Dönüşüm yolculuğu" subtitle="Ziyaretten alışverişe, her adım önemli."/><div className="space-y-6 rounded-lg border border-border bg-card p-6">{[{title:'Mağaza ziyareti',value:12847,width:'w-full',color:'bg-primary'},{title:'Ürün görüntüleme',value:4286,width:'w-2/3',color:'bg-primary/65'},{title:'Ödeme başlatma',value:617,width:'w-1/3',color:'bg-success'},{title:'Tamamlanan satış',value:214,width:'w-1/5',color:'bg-volt'}].map(s=><div key={s.title}><div className="mb-2 flex justify-between text-[11px]"><span className="text-muted-foreground">{s.title}</span><span className="font-semibold">{Math.round(s.value*multiplier).toLocaleString('tr')}</span></div><div className="h-2 overflow-hidden rounded-full bg-muted"><div className={`h-full rounded-full ${s.width} ${s.color}`}/></div></div>)}</div></section></div>
 <section className="mt-7"><SectionHeading title="Ürün performansı" subtitle="En iyi içeriklerin, en güçlü sonuçların."/><div className="overflow-x-auto rounded-lg border border-border bg-card"><table className="admin-table"><thead><tr><th>Ürün</th><th>Görüntülenme</th><th>Satış</th><th>Dönüşüm</th><th>Gelir</th><th>Değişim</th></tr></thead><tbody>{[{name:'Instagram Büyüme Rehberi',views:6124,sales:128,rate:'%2,1',income:31872,growth:'%24,8'},{name:'1:1 Strateji Görüşmesi',views:3218,sales:8,rate:'%0,2',income:11920,growth:'%12,2'},{name:'Reels Şablon Paketi',views:3505,sales:78,rate:'%2,2',income:31122,growth:'%18,4'}].map(p=><tr key={p.name}><td className="min-w-44 font-semibold">{p.name}</td><td>{Math.round(p.views*multiplier).toLocaleString('tr')}</td><td>{Math.round(p.sales*multiplier)}</td><td>{p.rate}</td><td className="whitespace-nowrap font-semibold">₺{Math.round(p.income*multiplier).toLocaleString('tr')}</td><td><span className="inline-flex items-center text-success"><ArrowUpRight className="h-3 w-3"/>{p.growth}</span></td></tr>)}</tbody></table></div></section>
 </AdminShell>}
