import { createFileRoute } from '@tanstack/react-router';
import { useState } from 'react';
import { Search, Download, Users, Heart, Wallet, UserRoundPlus, ArrowUpRight, Mail } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Dialog, DialogContent, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import { AdminShell } from '@/components/admin/AdminShell';
import { Person, Stat, EmptyState, Status } from '@/components/admin/Widgets';
import { customers, orders, exportCSV } from '@/lib/admin-data';
import { formatTRY } from '@/lib/store-data';
export const Route = createFileRoute('/customers')({head:()=>({meta:[{title:'Müşteriler — Sety'},{name:'description',content:'Müşterilerinizi, alışveriş geçmişlerini ve toplam harcamalarını keşfedin.'},{property:'og:title',content:'Müşteriler — Sety'},{property:'og:description',content:'Sety kitlenizi daha yakından tanıyın.'},{property:'og:type',content:'website'},{name:'twitter:card',content:'summary_large_image'}]}),component:CustomersPage});
function CustomersPage(){const [query,setQuery]=useState('');const [segment,setSegment]=useState('Tüm müşteriler');const [selected,setSelected]=useState<(typeof customers)[number]|null>(null);const filtered=customers.filter(c=>(segment!=='Tekrar alışveriş yapanlar'||c.orders>1)&&`${c.name} ${c.email}`.toLocaleLowerCase('tr').includes(query.toLocaleLowerCase('tr')));return <AdminShell title="Müşteriler" action={<Button variant="outline" className="bg-card text-xs" onClick={()=>exportCSV('sety-musteriler',[['Ad','E-posta','Sipariş','Toplam harcama'],...filtered.map(c=>[c.name,c.email,String(c.orders),String(c.spent)])])}><Download/>Listeyi dışa aktar</Button>}><div className="mb-7 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Stat label="Toplam müşteri" value="7" change="%14,3" icon={<Users className="h-4 w-4"/>}/><Stat label="Yeni müşteriler" value="6" change="%20" icon={<UserRoundPlus className="h-4 w-4"/>}/><Stat label="Tekrar alışveriş" value="%14,3" change="%4,2" icon={<Heart className="h-4 w-4"/>}/><Stat label="Ortalama harcama" value="₺433" change="%8,6" icon={<Wallet className="h-4 w-4"/>}/></div>
 <div className="mb-5 flex flex-wrap justify-between gap-4"><div className="flex gap-1 rounded-lg bg-muted p-1">{['Tüm müşteriler','Tekrar alışveriş yapanlar'].map(v=><Button key={v} variant="ghost" size="sm" className={`text-[11px] ${segment===v?'bg-card shadow-sm':'text-muted-foreground'}`} onClick={()=>setSegment(v)}>{v}</Button>)}</div><div className="relative w-full sm:w-64"><Search className="absolute left-3 top-3 h-3.5 w-3.5 text-subtle"/><input className="form-input pl-9" aria-label="Müşteri ara" placeholder="Ad veya e-posta ara…" value={query} onChange={e=>setQuery(e.target.value)}/></div></div><div className="overflow-x-auto rounded-lg border border-border bg-card"><table className="admin-table"><thead><tr><th>Müşteri</th><th>Sipariş</th><th>Toplam harcama</th><th>Kaynak</th><th>Son alışveriş</th><th/></tr></thead><tbody>{filtered.map(c=><tr key={c.email}><td><Person name={c.name} email={c.email}/></td><td>{c.orders}<span className="ml-2 text-subtle">sipariş</span></td><td className="font-semibold">{formatTRY(c.spent)}</td><td><span className="rounded bg-muted px-2 py-1 text-[10px] text-muted-foreground">{c.source}</span></td><td className="whitespace-nowrap text-muted-foreground">{c.last.split(',')[0]}</td><td><Button size="icon" variant="ghost" onClick={()=>setSelected(c)} aria-label={`${c.name} detayları`}><ArrowUpRight/></Button></td></tr>)}</tbody></table>{!filtered.length&&<EmptyState/>}</div><p className="mt-4 text-[10px] text-muted-foreground">{filtered.length} müşteri gösteriliyor</p>
 <Dialog open={!!selected} onOpenChange={open=>{if(!open)setSelected(null);}}><DialogContent><DialogTitle>Müşteri profili</DialogTitle><DialogDescription>Alışveriş geçmişi ve müşteri bilgileri</DialogDescription>{selected&&<><Person name={selected.name} email={selected.email}/><div className="my-2 grid grid-cols-2 border-y border-border py-4"><div><p className="text-[10px] text-muted-foreground">Toplam harcama</p><p className="mt-2 text-xl font-bold">{formatTRY(selected.spent)}</p></div><div><p className="text-[10px] text-muted-foreground">Sipariş sayısı</p><p className="mt-2 text-xl font-bold">{selected.orders}</p></div></div><h3 className="text-xs font-semibold">Alışveriş geçmişi</h3>{orders.filter(o=>o.email===selected.email).map(o=><div key={o.id} className="flex items-center justify-between gap-4 py-2"><div><p className="text-xs">{o.product}</p><p className="mt-1 text-[10px] text-subtle">{o.date} · {formatTRY(o.price)}</p></div><Status value={o.status}/></div>)}<Button asChild variant="outline"><a href={`mailto:${selected.email}`}><Mail/>E-posta gönder</a></Button></>}</DialogContent></Dialog>
 </AdminShell>}
