import { createFileRoute, Link } from '@tanstack/react-router';
import { useState } from 'react';
import { ArrowUpRight, Wallet, Eye, ShoppingBag, MousePointer2, Plus, ChevronRight, CalendarDays, BookOpen, Video, ArrowRight } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { AdminShell } from '@/components/admin/AdminShell';
import { Stat, SectionHeading, SalesChart, RangePicker, Person, Status } from '@/components/admin/Widgets';
import { orders } from '@/lib/admin-data';
import { formatTRY } from '@/lib/store-data';
import guideImage from '@/assets/growth-guide.jpg';
export const Route = createFileRoute('/dashboard')({head:()=>({meta:[{title:'Genel Bakış — Sety'},{name:'description',content:'Sety mağazanızın satışları, geliri ve son aktiviteleri.'},{property:'og:title',content:'Genel Bakış — Sety'},{property:'og:description',content:'İçerik üretici mağazanızın performans özeti.'},{property:'og:type',content:'website'},{name:'twitter:card',content:'summary_large_image'}]}),component:Dashboard});
function Dashboard(){const [range,setRange]=useState('Son 30 gün');const short=range==='Son 7 gün';return <AdminShell title="Genel Bakış" action={<div className="flex gap-2"><RangePicker value={range} onChange={setRange}/><Button asChild className="text-xs"><Link to="/store"><Plus/>Ürün Ekle</Link></Button></div>}>
 <div className="mb-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Stat label="Toplam gelir" value={short?'₺12.480':'₺48.320'} change="%18,2" icon={<Wallet className="h-4 w-4"/>}/><Stat label="Mağaza görüntülenme" value={short?'3.218':'12.847'} change="%9,4" icon={<Eye className="h-4 w-4"/>}/><Stat label="Toplam satış" value={short?'56':'214'} change="%12,1" icon={<ShoppingBag className="h-4 w-4"/>}/><Stat label="Dönüşüm oranı" value={short?'%4,6':'%4,8'} change="%0,6" icon={<MousePointer2 className="h-4 w-4"/>}/></div>
 <div className="grid gap-6 xl:grid-cols-[minmax(0,1fr)_290px]"><section className="min-w-0 border border-border bg-card p-5 sm:p-6 rounded-lg"><SectionHeading title="Gelir performansı" subtitle="Küçük adımlar, büyüyen bir iş." action={<span className="rounded bg-success/10 px-2 py-1 text-[10px] font-semibold text-success">↗ %18,2 artış</span>}/><div className="mb-5 flex items-baseline gap-3"><span className="font-display text-3xl font-bold">{short?'₺12.480':'₺48.320'}</span><span className="text-[10px] text-subtle">{range.toLowerCase()}</span></div><SalesChart range={range}/></section>
 <section className="min-w-0"><div className="flex h-full flex-col overflow-hidden rounded-lg bg-foreground text-primary-foreground"><div className="relative h-40 overflow-hidden"><img src={guideImage} width={1024} height={1024} alt="Mor kapaklı dijital pazarlama rehberi" className="h-full w-full object-cover object-[50%_55%]"/><span className="absolute left-4 top-4 rounded bg-volt px-2 py-1 text-[9px] font-bold text-volt-foreground">EN ÇOK SATAN</span></div><div className="flex flex-1 flex-col p-5"><p className="text-[10px] text-primary-foreground/50">Bu ayın yıldızı</p><h2 className="mt-2 text-lg font-bold leading-snug">Instagram<br/>Büyüme Rehberi</h2><div className="mt-4 flex gap-8"><div><p className="text-xl font-bold">128</p><p className="mt-1 text-[10px] text-primary-foreground/50">satış</p></div><div><p className="text-xl font-bold">₺31.872</p><p className="mt-1 text-[10px] text-primary-foreground/50">toplam gelir</p></div></div><Button asChild variant="ghost" className="mt-5 justify-between border-t border-primary-foreground/15 px-0 pt-4 text-[11px] hover:bg-transparent hover:text-volt"><Link to="/analytics">Ürün performansı<ArrowUpRight/></Link></Button></div></div></section></div>
 <div className="mt-7 grid gap-6 xl:grid-cols-[minmax(0,1fr)_290px]"><section className="min-w-0"><SectionHeading title="Son siparişler" subtitle="İçeriklerin birilerinin hayatına dokunuyor." action={<Button asChild variant="ghost" className="h-7 px-0 text-[11px] text-primary"><Link to="/orders">Tümünü gör<ArrowRight/></Link></Button>}/><div className="overflow-x-auto rounded-lg border border-border bg-card"><table className="admin-table"><thead><tr><th>Müşteri</th><th>Ürün</th><th>Tutar</th><th>Durum</th></tr></thead><tbody>{orders.slice(0,4).map(o=><tr key={o.id}><td><Person name={o.name} email={o.email}/></td><td className="max-w-48 text-muted-foreground">{o.product}</td><td className="whitespace-nowrap font-semibold">{formatTRY(o.price)}</td><td><Status value={o.status}/></td></tr>)}</tbody></table></div></section><section><SectionHeading title="Sıradaki adımın" subtitle="Mağazanı bir adım ileri taşı."/><div className="divide-y divide-border rounded-lg border border-border bg-card">{[{icon:BookOpen,title:'Yeni bir ürün yayınla',sub:'Bilgini bir gelire dönüştür.',to:'/store'},{icon:Video,title:'Mağazanı paylaş',sub:'Kitlenle bağlantı kur.',to:'/store'},{icon:CalendarDays,title:'Performansını keşfet',sub:'En iyi çalışanı bul.',to:'/analytics'}].map(({icon:I,title,sub,to})=><Button asChild key={title} variant="ghost" className="h-auto w-full justify-start whitespace-normal rounded-none p-4"><Link to={to as '/store'|'/analytics'}><span className="grid h-9 w-9 shrink-0 place-items-center rounded-lg bg-muted text-muted-foreground"><I/></span><span className="flex-1 text-left"><span className="block text-[11px] font-semibold">{title}</span><span className="mt-1 block text-[10px] text-subtle">{sub}</span></span><ChevronRight className="text-subtle"/></Link></Button>)}</div></section></div>
 </AdminShell>}
