import { createFileRoute } from '@tanstack/react-router';
import { useState } from 'react';
import { Download, Search, ArrowUpRight, ShoppingBag, Wallet, Clock3, RotateCcw } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Dialog, DialogContent, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import { AdminShell } from '@/components/admin/AdminShell';
import { Stat, Person, Status, EmptyState } from '@/components/admin/Widgets';
import { orders, exportCSV, type Order } from '@/lib/admin-data';
import { formatTRY } from '@/lib/store-data';
export const Route = createFileRoute('/orders')({head:()=>({meta:[{title:'Siparişler — Sety'},{name:'description',content:'Mağaza siparişlerini, ödeme durumlarını ve müşteri detaylarını inceleyin.'},{property:'og:title',content:'Siparişler — Sety'},{property:'og:description',content:'Sety satışlarınızın tüm detayları bir arada.'},{property:'og:type',content:'website'},{name:'twitter:card',content:'summary_large_image'}]}),component:OrdersPage});
function OrdersPage(){const [query,setQuery]=useState('');const [filter,setFilter]=useState('Tümü');const [selected,setSelected]=useState<Order|null>(null);const filtered=orders.filter(o=>(filter==='Tümü'||o.status===filter)&&`${o.name} ${o.id} ${o.email} ${o.product}`.toLocaleLowerCase('tr').includes(query.toLocaleLowerCase('tr')));return <AdminShell title="Siparişler" action={<Button variant="outline" className="bg-card text-xs" onClick={()=>exportCSV('sety-siparisler',[['Sipariş','Müşteri','E-posta','Ürün','Tutar','Durum','Tarih'],...filtered.map(o=>[o.id,o.name,o.email,o.product,String(o.price),o.status,o.date])])}><Download/>Dışa aktar</Button>}>
 <div className="mb-7 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Stat label="Toplam sipariş" value="8" change="%12,1" icon={<ShoppingBag className="h-4 w-4"/>}/><Stat label="Tahsil edilen" value={formatTRY(orders.filter(o=>o.status==='Ödendi').reduce((s,o)=>s+o.price,0))} change="%18,2" icon={<Wallet className="h-4 w-4"/>}/><Stat label="Bekleyen ödeme" value="1" change="%0" icon={<Clock3 className="h-4 w-4"/>}/><Stat label="İade edilen" value="1" change="%2,4" down icon={<RotateCcw className="h-4 w-4"/>}/></div>
 <div className="mb-5 flex flex-wrap items-center justify-between gap-4"><div className="flex flex-wrap gap-1 rounded-lg bg-muted p-1">{['Tümü','Ödendi','Bekliyor','İade edildi'].map(v=><Button key={v} size="sm" variant="ghost" onClick={()=>setFilter(v)} className={`text-[11px] ${filter===v?'bg-card text-foreground shadow-sm':'text-muted-foreground'}`}>{v}<span className="ml-1 text-[9px] text-subtle">{v==='Tümü'?orders.length:orders.filter(o=>o.status===v).length}</span></Button>)}</div><div className="relative w-full sm:w-64"><Search className="absolute left-3 top-3 h-3.5 w-3.5 text-subtle"/><input className="form-input pl-9" aria-label="Sipariş ara" placeholder="Sipariş veya müşteri ara…" value={query} onChange={e=>setQuery(e.target.value)}/></div></div>
 <div className="overflow-x-auto rounded-lg border border-border bg-card"><table className="admin-table"><thead><tr><th>Sipariş</th><th>Müşteri</th><th>Ürün</th><th>Tarih</th><th>Tutar</th><th>Durum</th><th/></tr></thead><tbody>{filtered.map(o=><tr key={o.id}><td><Button variant="link" className="h-auto p-0 text-[11px]" onClick={()=>setSelected(o)}>#{o.id}</Button></td><td><Person name={o.name} email={o.email}/></td><td className="min-w-40 text-muted-foreground">{o.product}</td><td className="whitespace-nowrap text-[10px] text-muted-foreground">{o.date.split(',')[0]}</td><td className="whitespace-nowrap font-semibold">{formatTRY(o.price)}</td><td><Status value={o.status}/></td><td><Button variant="ghost" size="icon" aria-label={`${o.id} detayları`} onClick={()=>setSelected(o)}><ArrowUpRight/></Button></td></tr>)}</tbody></table>{!filtered.length&&<EmptyState/>}</div><p className="mt-4 text-[10px] text-muted-foreground">{filtered.length} sipariş gösteriliyor</p>
 <Dialog open={!!selected} onOpenChange={open=>{if(!open)setSelected(null);}}><DialogContent><DialogTitle>Sipariş #{selected?.id}</DialogTitle><DialogDescription>Sipariş ve ödeme özeti</DialogDescription>{selected&&<><div className="flex items-center justify-between border-b border-border pb-5"><Person name={selected.name} email={selected.email}/><Status value={selected.status}/></div><dl className="space-y-4 text-xs">{[['Ürün',selected.product],['Sipariş tarihi',selected.date],['Trafik kaynağı',selected.source],['Ödeme yöntemi','Shopier / Kart'],['Toplam',formatTRY(selected.price)]].map(([label,value])=><div key={label} className="flex justify-between gap-6"><dt className="text-muted-foreground">{label}</dt><dd className="text-right font-medium">{value}</dd></div>)}</dl><div className="border-t border-border pt-4 text-[11px] text-muted-foreground">{selected.status==='Ödendi'?'Ödeme alındı · Dijital teslimat tamamlandı':selected.status==='Bekliyor'?'Ödeme tamamlanması bekleniyor':'İade işlemi tamamlandı'}</div></>}</DialogContent></Dialog>
 </AdminShell>}
