import { createFileRoute } from '@tanstack/react-router';
import { useState } from 'react';
import { UserRound, Bell, CreditCard, ShieldCheck, Check, ExternalLink, Sparkles, Mail } from 'lucide-react';
import { toast } from 'sonner';
import { Button } from '@/components/ui/button';
import { Switch } from '@/components/ui/switch';
import { AdminShell } from '@/components/admin/AdminShell';
import { useAdmin } from '@/components/admin/AdminContext';
import { SectionHeading } from '@/components/admin/Widgets';
export const Route = createFileRoute('/settings')({head:()=>({meta:[{title:'Ayarlar — Sety'},{name:'description',content:'Profil, bildirim, ödeme ve plan ayarlarınızı yönetin.'},{property:'og:title',content:'Ayarlar — Sety'},{property:'og:description',content:'Sety çalışma alanınızı kendinize göre düzenleyin.'},{property:'og:type',content:'website'},{name:'twitter:card',content:'summary_large_image'}]}),component:SettingsPage});
function SettingsPage(){const {profile,setProfile,notifications,setNotifications}=useAdmin();const [draft,setDraft]=useState(profile);const [tab,setTab]=useState('Profil');return <AdminShell title="Ayarlar"><div className="grid items-start gap-8 md:grid-cols-[180px_minmax(0,1fr)]"><nav className="flex flex-wrap gap-1 md:flex-col">{[{title:'Profil',icon:UserRound},{title:'Bildirimler',icon:Bell},{title:'Ödemeler',icon:CreditCard},{title:'Plan & faturalama',icon:Sparkles},{title:'Güvenlik',icon:ShieldCheck}].map(({title,icon:I})=><Button key={title} variant="ghost" className={`justify-start text-xs ${tab===title?'bg-accent text-primary':'text-muted-foreground'}`} onClick={()=>setTab(title)}><I/>{title}</Button>)}</nav><div className="max-w-2xl">
 {tab==='Profil'&&<form onSubmit={e=>{e.preventDefault();setProfile(draft);toast.success('Profil bilgileri güncellendi');}}><SectionHeading title="Kişisel bilgiler" subtitle="Hesabını ve mağaza kimliğini yönet."/><div className="mb-7 flex items-center gap-4 border-b border-border pb-6"><span className="grid h-16 w-16 place-items-center rounded-full bg-accent text-xl font-semibold text-primary">EY</span><div><p className="text-sm font-semibold">{profile.name}</p><p className="mt-1 text-xs text-muted-foreground">İçerik üreticisi · Founder</p></div></div><div className="space-y-5"><div><label className="form-label" htmlFor="settings-name">Ad soyad</label><input id="settings-name" className="form-input" required value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})}/></div><div><label className="form-label" htmlFor="settings-email">E-posta adresi</label><input id="settings-email" className="form-input" required type="email" value={draft.email} onChange={e=>setDraft({...draft,email:e.target.value})}/></div><div><label className="form-label" htmlFor="settings-username">Mağaza kullanıcı adı</label><div className="flex items-center rounded-md border border-border bg-card"><span className="border-r border-border px-3 text-xs text-muted-foreground">sety.store/</span><input id="settings-username" className="form-input border-0" required pattern="[a-z0-9_-]+" value={draft.username} onChange={e=>setDraft({...draft,username:e.target.value})}/></div></div><div><label className="form-label" htmlFor="settings-bio">Biyografi</label><textarea id="settings-bio" className="form-input min-h-28" value={draft.bio} maxLength={200} onChange={e=>setDraft({...draft,bio:e.target.value})}/></div><div className="flex justify-end border-t border-border pt-5"><Button type="submit" className="text-xs"><Check/>Değişiklikleri kaydet</Button></div></div></form>}
 {tab==='Bildirimler'&&<><SectionHeading title="Bildirim tercihleri" subtitle="Senin için önemli gelişmelerden haberdar ol."/>{[{title:'Yeni siparişler',sub:'Her yeni satışta e-posta bildirimi.'},{title:'Haftalık performans özeti',sub:'Gelir ve mağaza istatistiklerinin haftalık özeti.'},{title:'Sety haberleri',sub:'Yeni özellikler, ürün güncellemeleri ve öneriler.'}].map((n,i)=><div key={n.title} className="flex items-center justify-between gap-6 border-b border-border py-6"><div><label htmlFor={`notification-${i}`} className="text-xs font-semibold">{n.title}</label><p className="mt-2 text-[11px] text-muted-foreground">{n.sub}</p></div><Switch id={`notification-${i}`} checked={notifications[i]} onCheckedChange={v=>setNotifications(ns=>ns.map((value,index)=>index===i?v:value))}/></div>)}<Button className="mt-6 text-xs" onClick={()=>toast.success('Bildirim tercihleri kaydedildi')}><Check/>Tercihleri kaydet</Button></>}
 {tab==='Ödemeler'&&<><SectionHeading title="Ödeme yöntemleri" subtitle="Mağazana ödeme almayı etkinleştir."/><div className="flex items-center justify-between border-y border-border py-6"><div className="flex items-center gap-3"><span className="grid h-11 w-11 place-items-center rounded-lg bg-accent text-primary"><CreditCard/></span><div><h3 className="text-sm font-semibold">Shopier</h3><p className="mt-1 text-xs text-muted-foreground">Kart ile güvenli ödeme</p></div></div><span className="rounded bg-muted px-2 py-1 text-[10px] text-muted-foreground">Bağlı değil</span></div><div className="py-6"><p className="text-xs leading-6 text-muted-foreground">Bu mağaza şu an örnek modda. Gerçek ödeme almak için Shopier bağlantısının ayrıca kurulması gerekiyor.</p><Button asChild variant="outline" className="mt-5 text-xs"><a href="https://www.shopier.com" target="_blank" rel="noreferrer">Shopier'i aç<ExternalLink/></a></Button></div></>}
 {tab==='Plan & faturalama'&&<><SectionHeading title="Plan & faturalama" subtitle="İçerik üretici yolculuğuna uygun plan."/><div className="border-y border-border py-6"><div className="flex justify-between"><span className="text-lg font-semibold">Founder Planı</span><span className="rounded bg-volt px-2 py-1 text-[10px] font-semibold text-volt-foreground">Deneme sürümü</span></div><p className="mt-2 text-xs text-muted-foreground">14 günlük deneme · 5 gün kaldı</p><div className="my-5 h-1.5 rounded-full bg-muted"><div className="h-full w-[64%] rounded-full bg-primary"/></div>{['Dijital ürün mağazası','Mağaza performans raporları','Müşteri ve sipariş yönetimi'].map(item=><p className="mt-3 flex items-center gap-2 text-xs" key={item}><Check className="h-3.5 w-3.5 text-success"/>{item}</p>)}</div><p className="mt-6 text-xs text-muted-foreground">Henüz aktif bir aboneliğin veya kayıtlı ödeme kartın yok.</p></>}
 {tab==='Güvenlik'&&<><SectionHeading title="Hesap güvenliği" subtitle="Hesabının koruması senin kontrolünde."/><div className="flex items-center gap-4 border-y border-border py-6"><ShieldCheck className="h-8 w-8 text-primary"/><div><p className="text-xs font-semibold">Örnek çalışma alanı</p><p className="mt-2 text-xs text-muted-foreground">Oturum açma ve şifre yönetimi henüz etkin değil.</p></div></div><div className="mt-7"><h3 className="text-sm font-semibold">Destek</h3><p className="mt-2 text-xs text-muted-foreground">Hesabınla ilgili yardım için Sety desteğine ulaş.</p><Button asChild variant="outline" className="mt-4 text-xs"><a href="mailto:destek@sety.store"><Mail/>Destek ile iletişime geç</a></Button></div></>}
 </div></div></AdminShell>}
