import { createFileRoute } from '@tanstack/react-router';
import { useState } from 'react';
import { Plus, BookOpen, Video, Link2, MoreHorizontal, Pencil, Trash2, ArrowUp, ArrowDown, Check, Smartphone, Palette, UserRound } from 'lucide-react';
import { toast } from 'sonner';
import { Button } from '@/components/ui/button';
import { Switch } from '@/components/ui/switch';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuTrigger } from '@/components/ui/dropdown-menu';
import { AdminShell } from '@/components/admin/AdminShell';
import { useAdmin } from '@/components/admin/AdminContext';
import { SectionHeading } from '@/components/admin/Widgets';
import { Storefront } from '@/components/Storefront';
import { formatTRY, type Product } from '@/lib/store-data';
import guideImage from '@/assets/growth-guide.jpg';
export const Route = createFileRoute('/store')({head:()=>({meta:[{title:'Mağazam — Sety'},{name:'description',content:'Ürünlerinizi, mağaza profilinizi ve görünümünüzü düzenleyin.'},{property:'og:title',content:'Mağazam — Sety'},{property:'og:description',content:'İçeriklerinizi şık bir Sety mağazasında sunun.'},{property:'og:type',content:'website'},{name:'twitter:card',content:'summary_large_image'}]}),component:StorePage});
function StorePage(){
 const {products,setProducts,profile,setProfile,announcement,setAnnouncement}=useAdmin();const [tab,setTab]=useState('Ürünler');const [editing,setEditing]=useState<Product|null>(null);const [deleteId,setDeleteId]=useState<string|null>(null);
 const create=()=>setEditing({id:'',title:'',subtitle:'',price:0,type:'Dijital İndirme',published:false,emoji:'📘'});
 const save=()=>{if(!editing)return;setProducts(ps=>editing.id?ps.map(p=>p.id===editing.id?editing:p):[...ps,{...editing,id:crypto.randomUUID()}]);setEditing(null);toast.success('Ürün kaydedildi');};
 const move=(id:string,direction:number)=>setProducts(ps=>{const copy=[...ps];const index=copy.findIndex(p=>p.id===id),other=index+direction;const a=copy[index],b=copy[other];if(a&&b){copy[index]=b;copy[other]=a;}return copy;});
 return <AdminShell title="Mağazam" action={<Button onClick={create} className="text-xs"><Plus/>Ürün Ekle</Button>}><div className="mb-7 flex items-center gap-6 border-b border-border">{[{title:'Ürünler',icon:BookOpen},{title:'Profil',icon:UserRound},{title:'Görünüm',icon:Palette}].map(({title,icon:I})=><Button key={title} variant="ghost" onClick={()=>setTab(title)} className={`h-11 rounded-none border-b-2 px-0 text-xs hover:bg-transparent ${tab===title?'border-primary text-primary':'border-transparent text-muted-foreground'}`}><I/>{title}{title==='Ürünler'&&<span className="rounded bg-muted px-1.5 py-0.5 text-[10px]">{products.length}</span>}</Button>)}</div>
 <div className="grid items-start gap-8 xl:grid-cols-[minmax(0,1fr)_310px]"><div className="min-w-0">
 {tab==='Ürünler'&&<><SectionHeading title="Ürünlerin" subtitle={`${products.filter(p=>p.published).length} yayında · ${products.filter(p=>!p.published).length} taslak`}/><div className="space-y-3">{products.map((p,index)=>{const I=p.type==='Koçluk'?Video:p.type==='Link'?Link2:BookOpen;return <div key={p.id} className="flex flex-wrap items-center gap-4 rounded-lg border border-border bg-card p-4"><span className="hidden text-[10px] text-subtle sm:block">{String(index+1).padStart(2,'0')}</span>{p.id==='p1'?<img src={guideImage} alt="Rehber kapağı" width={1024} height={1024} className="h-16 w-14 rounded object-cover"/>:<div className={`grid h-16 w-14 shrink-0 place-items-center rounded ${p.type==='Koçluk'?'bg-volt/25 text-volt-foreground':'bg-accent text-primary'}`}><I className="h-6 w-6" strokeWidth={1.5}/></div>}<div className="min-w-0 flex-1"><span className="text-[9px] text-muted-foreground">{p.type}</span><h3 className="mt-1 text-xs font-semibold">{p.title}</h3><p className="mt-1 text-[10px] text-muted-foreground">{p.subtitle}</p><p className="mt-2 text-xs font-semibold text-primary">{formatTRY(p.price)}</p></div><div className="flex items-center gap-2"><span className="text-[10px] text-muted-foreground">{p.published?'Yayında':'Taslak'}</span><Switch aria-label={`${p.title} yayın durumu`} checked={p.published} onCheckedChange={checked=>setProducts(ps=>ps.map(item=>item.id===p.id?{...item,published:checked}:item))}/><DropdownMenu><DropdownMenuTrigger asChild><Button variant="ghost" size="icon" aria-label={`${p.title} işlemleri`}><MoreHorizontal/></Button></DropdownMenuTrigger><DropdownMenuContent align="end"><DropdownMenuItem onClick={()=>setEditing({...p})}><Pencil className="mr-2 h-4 w-4"/>Düzenle</DropdownMenuItem><DropdownMenuItem disabled={index===0} onClick={()=>move(p.id,-1)}><ArrowUp className="mr-2 h-4 w-4"/>Yukarı taşı</DropdownMenuItem><DropdownMenuItem disabled={index===products.length-1} onClick={()=>move(p.id,1)}><ArrowDown className="mr-2 h-4 w-4"/>Aşağı taşı</DropdownMenuItem><DropdownMenuItem className="text-destructive" onClick={()=>setDeleteId(p.id)}><Trash2 className="mr-2 h-4 w-4"/>Sil</DropdownMenuItem></DropdownMenuContent></DropdownMenu></div></div>})}</div><Button onClick={create} variant="outline" className="mt-4 h-14 w-full border-dashed bg-transparent text-xs text-muted-foreground"><Plus/>Yeni ürün ekle</Button><p className="mt-4 text-[10px] text-muted-foreground">İlk sıradaki yayınlanmış ürün, mağazanda öne çıkar.</p></>}
 {tab==='Profil'&&<form onSubmit={e=>{e.preventDefault();toast.success('Mağaza profili güncellendi');}} className="space-y-6"><SectionHeading title="Mağaza profili" subtitle="Kitlenin seni tanıdığı yer."/><div><label className="form-label" htmlFor="store-name">Görünen ad</label><input id="store-name" className="form-input" value={profile.name} required onChange={e=>setProfile({...profile,name:e.target.value})}/></div><div><label className="form-label" htmlFor="store-bio">Biyografi</label><textarea id="store-bio" className="form-input min-h-28" maxLength={200} value={profile.bio} onChange={e=>setProfile({...profile,bio:e.target.value})}/><p className="mt-2 text-right text-[10px] text-subtle">{profile.bio.length}/200</p></div><div><label className="form-label" htmlFor="announcement">Duyuru</label><input id="announcement" className="form-input" value={announcement} onChange={e=>setAnnouncement(e.target.value)}/></div><Button type="submit" className="text-xs"><Check/>Değişiklikleri kaydet</Button></form>}
 {tab==='Görünüm'&&<><SectionHeading title="Mağaza teması" subtitle="Markana yakışan, dikkat çeken bir görünüm."/><div className="overflow-hidden rounded-lg border-2 border-primary"><div className="bg-store-bg p-8 text-store-text"><span className="text-xs text-store-accent">EMİRHAN'IN MAĞAZASI</span><p className="mt-3 font-[family-name:var(--font-serif-display)] text-3xl">İçerikten ilhama.</p><div className="mt-5 grid grid-cols-2 gap-3"><div className="h-16 rounded-lg bg-store-tile"/><div className="h-16 rounded-lg bg-store-tile"/></div></div><div className="flex items-center justify-between bg-card p-4"><div><h3 className="text-xs font-semibold">Gece · İkonlu Bento</h3><p className="mt-1 text-[10px] text-muted-foreground">Instrument Serif + Work Sans</p></div><span className="flex items-center gap-1 text-xs text-primary"><Check className="h-4 w-4"/>Seçili</span></div></div><div className="mt-6 flex items-center gap-3"><span className="text-xs text-muted-foreground">Tema renkleri</span>{['bg-store-bg','bg-store-tile','bg-store-accent','bg-store-text'].map(c=><span key={c} className={`h-7 w-7 rounded-full border border-border ${c}`}/>)}</>}
 </div><div className="mx-auto w-full max-w-[310px]"><SectionHeading title="Mağaza önizlemesi" action={<Smartphone className="h-4 w-4 text-subtle"/>}/><div className="overflow-hidden rounded-[36px] border-[7px] border-foreground bg-store-bg shadow-lg"><div className="relative h-[570px] overflow-y-auto overflow-x-hidden"><Storefront products={products} compact profile={profile} announcement={announcement}/></div></div><div className="mt-4 flex items-center justify-center gap-1.5 text-[10px] text-success"><span className="h-1.5 w-1.5 rounded-full bg-success"/>Değişiklikler anında önizlenir</div></div></div>
 <Dialog open={!!editing} onOpenChange={open=>{if(!open)setEditing(null);}}><DialogContent className="max-w-md"><DialogHeader><DialogTitle>{editing?.id?'Ürünü düzenle':'Yeni ürün'}</DialogTitle><DialogDescription>Ürünün bilgilerini ve yayın durumunu belirle.</DialogDescription></DialogHeader>{editing&&<form onSubmit={e=>{e.preventDefault();save();}} className="space-y-4"><div><label htmlFor="product-title" className="form-label">Ürün adı</label><input id="product-title" required className="form-input" value={editing.title} onChange={e=>setEditing({...editing,title:e.target.value})}/></div><div><label htmlFor="product-subtitle" className="form-label">Kısa açıklama</label><input id="product-subtitle" required className="form-input" value={editing.subtitle} onChange={e=>setEditing({...editing,subtitle:e.target.value})}/></div><div className="grid grid-cols-2 gap-4"><div><label htmlFor="product-type" className="form-label">Ürün türü</label><select id="product-type" className="form-input" value={editing.type} onChange={e=>setEditing({...editing,type:e.target.value as Product['type']})}><option>Dijital İndirme</option><option>Koçluk</option><option>Link</option></select></div><div><label htmlFor="product-price" className="form-label">Fiyat (₺)</label><input id="product-price" type="number" min="0" step="1" required className="form-input" value={editing.price} onChange={e=>setEditing({...editing,price:Number(e.target.value)})}/></div></div><div className="flex justify-between py-2"><label className="text-xs" htmlFor="product-published">Mağazada yayınla</label><Switch id="product-published" checked={editing.published} onCheckedChange={checked=>setEditing({...editing,published:checked})}/></div><Button type="submit" className="w-full"><Check/>Kaydet</Button></form>}</DialogContent></Dialog>
 <Dialog open={!!deleteId} onOpenChange={open=>{if(!open)setDeleteId(null);}}><DialogContent className="max-w-sm"><DialogTitle>Ürün silinsin mi?</DialogTitle><DialogDescription>Ürün mağazandan ve önizlemeden kaldırılacak.</DialogDescription><div className="flex justify-end gap-2"><Button variant="outline" onClick={()=>setDeleteId(null)}>Vazgeç</Button><Button variant="destructive" onClick={()=>{setProducts(ps=>ps.filter(p=>p.id!==deleteId));setDeleteId(null);toast.success('Ürün silindi');}}>Sil</Button></div></DialogContent></Dialog>
 </AdminShell>
}
