import { Link, useRouterState } from '@tanstack/react-router';
import { useState, type ReactNode } from 'react';
import { LayoutGrid, Store, ShoppingBag, Users, ChartNoAxesCombined, Settings, Copy, ArrowUpRight, ChevronRight, Menu, X, ChevronsUpDown, CircleHelp, Sparkles, Bell, Check } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { toast } from 'sonner';
import { useAdmin } from './AdminContext';
const navigation = [
 { label:'Genel Bakış', to:'/dashboard', icon:LayoutGrid }, { label:'Mağazam', to:'/store', icon:Store }, { label:'Siparişler', to:'/orders', icon:ShoppingBag }, { label:'Müşteriler', to:'/customers', icon:Users }, { label:'Analitik', to:'/analytics', icon:ChartNoAxesCombined }, { label:'Ayarlar', to:'/settings', icon:Settings },
] as const;
export function AdminShell({ title, children, action }: { title: string; children: ReactNode; action?: ReactNode }) {
 const pathname = useRouterState({select:s=>s.location.pathname}); const [mobile,setMobile] = useState(false); const [alerts,setAlerts] = useState(false); const { profile } = useAdmin();
 const copy = async () => { try { await navigator.clipboard.writeText(`${window.location.origin}/${profile.username}`); toast.success('Mağaza bağlantısı kopyalandı'); } catch { toast.error('Bağlantı kopyalanamadı'); } };
 return <div className="admin-app min-h-screen bg-background text-foreground">
 {mobile && <div className="fixed inset-0 z-40 bg-scrim lg:hidden" onClick={()=>setMobile(false)} />}
 <aside className={`admin-sidebar fixed inset-y-0 left-0 z-50 flex w-[232px] flex-col border-r border-border bg-card px-4 py-7 transition-transform lg:translate-x-0 ${mobile?'translate-x-0':'-translate-x-full'}`}>
 <div className="flex items-center gap-2.5 px-3"><span className="sety-mark grid h-9 w-9 place-items-center rounded-lg bg-primary text-xl font-extrabold text-primary-foreground">s</span><span className="font-display text-[27px] font-extrabold">sety<span className="text-primary">.</span></span><span className="ml-1 rounded bg-volt px-1.5 py-0.5 text-[9px] font-extrabold text-volt-foreground">BETA</span><Button variant="ghost" size="icon" className="ml-auto lg:hidden" onClick={()=>setMobile(false)} aria-label="Menüyü kapat"><X /></Button></div>
 <div className="mt-8 flex items-center gap-2 rounded-lg border border-border p-2.5"><span className="h-1.5 w-1.5 shrink-0 rounded-full bg-success"/><span className="min-w-0 flex-1 truncate text-[11px] font-medium">sety.store/{profile.username}</span><Button variant="ghost" size="icon" className="h-6 w-6 text-muted-foreground" onClick={copy} title="Bağlantıyı kopyala" aria-label="Bağlantıyı kopyala"><Copy className="!h-3 !w-3"/></Button></div>
 <p className="mb-3 mt-8 px-3 text-[10px] font-semibold uppercase tracking-[0.12em] text-subtle">Çalışma alanı</p>
 <nav className="space-y-1.5">{navigation.map(({label,to,icon:I})=><Button key={to} asChild variant="ghost" className={`h-11 w-full justify-start gap-3 px-3 font-medium ${pathname===to?'bg-accent text-primary':'text-muted-foreground'}`}><Link to={to} onClick={()=>setMobile(false)}><I className="!h-[18px] !w-[18px]"/>{label}{to==='/orders'&&<span className="ml-auto grid h-5 min-w-5 place-items-center rounded bg-muted text-[10px] text-muted-foreground">8</span>}{pathname===to&&to!=='/orders'&&<span className="ml-auto h-1 w-1 rounded-full bg-primary"/>}</Link></Button>)}</nav>
 <div className="mt-auto pt-10"><div className="rounded-lg border border-border bg-muted/40 p-3.5"><div className="flex items-center gap-2 text-xs font-semibold"><Sparkles className="h-4 w-4 text-primary"/>Founder Planı<span className="ml-auto text-[10px] text-muted-foreground">9 / 14 gün</span></div><div className="my-3 h-1 rounded-full bg-border"><div className="h-1 w-[64%] rounded-full bg-primary"/></div><Button asChild variant="ghost" className="h-7 w-full justify-between px-0 text-xs text-primary"><Link to="/settings" search={{}} >Planı incele<ArrowUpRight/></Link></Button></div><Button asChild variant="ghost" className="mt-4 w-full justify-start text-xs text-muted-foreground"><Link to="/settings"><CircleHelp/>Yardım & destek</Link></Button><div className="mt-4 border-t border-border pt-4"><Button asChild variant="ghost" className="h-auto w-full justify-start p-1"><Link to="/settings"><span className="grid h-9 w-9 shrink-0 place-items-center rounded-full bg-accent text-xs font-bold text-primary">EY</span><span className="min-w-0 flex-1 text-left"><span className="block truncate text-xs font-semibold">{profile.name}</span><span className="mt-1 block text-[10px] text-muted-foreground">İçerik üreticisi</span></span><ChevronsUpDown className="text-subtle"/></Link></Button></div></div>
 </aside>
 <div className="lg:ml-[232px]"><header className="relative z-30 flex h-[76px] items-center justify-between gap-4 border-b border-border bg-card/90 px-5 lg:px-8"><div className="flex min-w-0 items-center gap-3"><Button variant="ghost" size="icon" className="lg:hidden" onClick={()=>setMobile(true)} aria-label="Menüyü aç"><Menu/></Button><div className="flex items-center gap-2 text-xs"><span className="hidden text-subtle sm:block">Çalışma alanı</span><ChevronRight className="hidden h-3 w-3 text-subtle sm:block"/><span className="font-medium">{title}</span></div></div><div className="flex items-center gap-2 sm:gap-4"><span className="hidden rounded border border-border bg-muted/50 px-2 py-1 text-[10px] text-muted-foreground sm:block">Örnek mağaza</span><div className="relative"><Button variant="ghost" size="icon" aria-label="Bildirimler" onClick={()=>setAlerts(!alerts)}><Bell className="text-muted-foreground"/><span className="absolute right-2 top-2 h-1.5 w-1.5 rounded-full bg-primary"/></Button>{alerts&&<div className="absolute right-0 top-12 w-72 rounded-lg border border-border bg-card p-4 shadow-lg"><h3 className="text-sm font-semibold">Bildirimler</h3><div className="mt-4 flex gap-3"><span className="grid h-8 w-8 shrink-0 place-items-center rounded-full bg-success/10 text-success"><Check className="h-4 w-4"/></span><div><p className="text-xs font-medium">Yeni bir satışın var!</p><p className="mt-1 text-[11px] text-muted-foreground">Zeynep, Instagram Büyüme Rehberi aldı.</p></div></div></div>}</div><span className="h-5 w-px bg-border"/><Button asChild variant="outline" className="text-xs"><Link to="/$username" params={{username:profile.username}}>Mağazayı Gör<ArrowUpRight/></Link></Button></div></header>
 <main className="mx-auto max-w-[1500px] px-5 py-7 sm:px-8 lg:py-8"><div className="mb-7 flex flex-wrap items-start justify-between gap-4"><div><p className="mb-2 text-[11px] text-muted-foreground">Emirhan'ın çalışma alanı</p><h1 className="font-display text-[28px] font-bold leading-tight">{title==='Genel Bakış'?'İyi ki geldin, Emirhan':title}<span className="text-primary">.</span></h1><p className="mt-2 text-xs text-muted-foreground">{{'Genel Bakış':'Mağazanda bugün neler oluyor, bir göz atalım.','Mağazam':'Senin içeriklerin. Senin markan. Senin mağazan.','Siparişler':'Her satışın hikâyesi, tek bir yerde.','Müşteriler':'İçeriklerini seven insanları daha yakından tanı.','Analitik':'Rakamların arkasındaki fırsatları keşfet.','Ayarlar':'Çalışma alanını kendine göre düzenle.'}[title]}</p></div>{action}</div>{children}<footer className="mt-10 flex flex-wrap justify-between gap-2 border-t border-border pt-5 text-[10px] text-subtle"><span>© 2026 Sety · İçerikten değere.</span><span>Örnek veriler · Değişiklikler bu oturumda geçerli</span></footer></main></div>
 </div>;
}
