import { useId, type ReactNode } from 'react';
import { ArrowUpRight, ArrowDownRight, ChevronDown } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuTrigger } from '@/components/ui/dropdown-menu';
import { initials } from '@/lib/admin-data';
export function RangePicker({value,onChange}:{value:string;onChange:(v:string)=>void}){return <DropdownMenu><DropdownMenuTrigger asChild><Button variant="outline" className="bg-card text-xs">{value}<ChevronDown/></Button></DropdownMenuTrigger><DropdownMenuContent align="end">{['Son 7 gün','Son 30 gün','Son 90 gün'].map(v=><DropdownMenuItem key={v} onClick={()=>onChange(v)}>{v}</DropdownMenuItem>)}</DropdownMenuContent></DropdownMenu>}
export function Stat({label,value,change,icon,chart,down=false}:{label:string;value:string;change:string;icon:ReactNode;chart?:boolean;down?:boolean}){return <div className="relative min-w-0 overflow-hidden rounded-lg border border-border bg-card p-5"><div className="mb-5 flex items-center justify-between gap-2"><span className="text-[11px] font-medium text-muted-foreground">{label}</span><span className="text-subtle">{icon}</span></div><div className="font-display text-[26px] font-bold">{value}</div><div className="mt-2 flex items-center gap-1.5 text-[10px]"><span className={`inline-flex items-center font-semibold ${down?'text-destructive':'text-success'}`}>{down?<ArrowDownRight className="h-3 w-3"/>:<ArrowUpRight className="h-3 w-3"/>}{change}</span><span className="text-subtle">önceki döneme göre</span></div>{chart&&<svg viewBox="0 0 80 30" className="absolute bottom-8 right-4 h-8 w-16 text-primary/60" aria-hidden="true"><path d="M0 26L10 22L20 25L30 12L40 17L50 9L60 12L70 2L80 5" fill="none" stroke="currentColor" strokeWidth="2"/></svg>}</div>}
export function SectionHeading({title,subtitle,action}:{title:string;subtitle?:string;action?:ReactNode}){return <div className="mb-5 flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-sm font-bold">{title}</h2>{subtitle&&<p className="mt-1 text-[11px] text-muted-foreground">{subtitle}</p>}</div>{action}</div>}
export function SalesChart({range='Son 30 gün',metric='Gelir'}:{range?:string;metric?:string}){
 const id=useId().replaceAll(':',''); const values=range==='Son 7 gün'?[35,60,42,80,58,115,98,140,160]:range==='Son 90 gün'?[30,80,65,125,95,80,150,125,145,185,150,170,200]:[45,42,72,50,60,38,90,75,105,66,125,102,146,95,118,100,158,127,180,150,174];
 const points=values.map((v,i)=>`${50+i/(values.length-1)*750},${230-v}`).join(' ');
 return <div className="w-full"><svg viewBox="0 0 830 275" className="h-auto max-h-[300px] w-full overflow-visible" role="img" aria-label={`${range} ${metric.toLowerCase()} grafiği`}><defs><linearGradient id={id} x1="0" x2="0" y1="0" y2="1"><stop offset="0%" stopColor="var(--primary)" stopOpacity=".12"/><stop offset="100%" stopColor="var(--primary)" stopOpacity="0"/></linearGradient></defs>{[30,80,130,180,230].map((y,i)=><g key={y}><line x1="50" y1={y} x2="800" y2={y} stroke="var(--border)" strokeDasharray="3 5"/><text x="0" y={y+4} fill="var(--muted-foreground)" fontSize="10">{metric==='Gelir'?['₺8.000','₺6.000','₺4.000','₺2.000','₺0'][i]:['800','600','400','200','0'][i]}</text></g>)}<polyline points={`50,230 ${points} 800,230`} fill={`url(#${id})`} stroke="none"/><polyline points={values.map((v,i)=>`${50+i/(values.length-1)*750},${240-v*.72}`).join(' ')} fill="none" stroke="var(--border)" strokeWidth="2" strokeDasharray="5 5"/><polyline points={points} fill="none" stroke="var(--primary)" strokeWidth="2.5" strokeLinejoin="round" strokeLinecap="round"/>{(range==='Son 7 gün'?['3 Eki','4 Eki','5 Eki','6 Eki','7 Eki','8 Eki','9 Eki']:['10 Eyl','15 Eyl','20 Eyl','25 Eyl','30 Eyl','5 Eki','9 Eki']).map((label,i)=><text key={label} x={50+i*125} y="264" fill="var(--muted-foreground)" fontSize="10" textAnchor={i===6?'end':'start'}>{label}</text>)}</svg><div className="mt-3 flex justify-center gap-6 text-[10px] text-muted-foreground"><span className="flex items-center gap-2"><span className="h-1.5 w-1.5 rounded-full bg-primary"/>Bu dönem</span><span className="flex items-center gap-2"><span className="h-1.5 w-1.5 rounded-full bg-border"/>Önceki dönem</span></div></div>
}
export function Person({name,email}:{name:string;email?:string}){return <div className="flex items-center gap-3"><span className="grid h-9 w-9 shrink-0 place-items-center rounded-full bg-accent text-[11px] font-semibold text-primary">{initials(name)}</span><div className="min-w-0"><span className="block text-xs font-semibold">{name}</span>{email&&<span className="mt-1 block text-[10px] text-muted-foreground">{email}</span>}</div></div>}
export function Status({value}:{value:string}){return <span className={`inline-flex items-center gap-1.5 whitespace-nowrap rounded px-2 py-1 text-[10px] font-medium ${value==='Ödendi'?'bg-success/10 text-success':value==='Bekliyor'?'bg-volt/30 text-volt-foreground':'bg-muted text-muted-foreground'}`}><span className="h-1 w-1 rounded-full bg-current"/>{value}</span>}
export function EmptyState(){return <div className="py-16 text-center"><p className="text-sm font-semibold">Sonuç bulunamadı</p><p className="mt-2 text-xs text-muted-foreground">Aramanı veya seçtiğin filtreyi değiştir.</p></div>}
